package DateApp;


/**
* DateApp/DateInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Date.idl
* 18 February 2017 12:33:59 o'clock GMT
*/

public interface DateInterfaceOperations 
{
} // interface DateInterfaceOperations
