package DateApp;


/**
* DateApp/DateInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Date.idl
* 18 February 2017 12:33:59 o'clock GMT
*/

public interface DateInterface extends DateInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DateInterface
