package SampleCA1;


/**
* SampleCA1/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SampleCA1.idl
* 18 February 2017 14:37:53 o'clock GMT
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
