package SampleCA1;


/**
* SampleCA1/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SampleCA1.idl
* 18 February 2017 14:37:53 o'clock GMT
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
