package SampleCA1;

/**
* SampleCA1/HelloHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SampleCA1.idl
* 18 February 2017 14:37:53 o'clock GMT
*/

public final class HelloHolder implements org.omg.CORBA.portable.Streamable
{
  public SampleCA1.Hello value = null;

  public HelloHolder ()
  {
  }

  public HelloHolder (SampleCA1.Hello initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SampleCA1.HelloHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SampleCA1.HelloHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SampleCA1.HelloHelper.type ();
  }

}
