package CA1;

/**
* CA1/AddHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CA1.idl
* 25 February 2017 12:12:40 o'clock GMT
*/

public final class AddHolder implements org.omg.CORBA.portable.Streamable
{
  public CA1.Add value = null;

  public AddHolder ()
  {
  }

  public AddHolder (CA1.Add initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CA1.AddHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CA1.AddHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CA1.AddHelper.type ();
  }

}
