package CA1;


/**
* CA1/Add.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CA1.idl
* 25 February 2017 12:12:40 o'clock GMT
*/

public interface Add extends AddOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Add
