package CA1;


/**
* CA1/AddOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CA1.idl
* 25 February 2017 12:12:40 o'clock GMT
*/

public interface AddOperations 
{
  int addTwoNumbers (int a, int b);
} // interface AddOperations
